### ISSUE TITLE
Unexpected Filters behavior

### ISSUE THREAD

**Issue by JBBianchi** [neuroglia-io/cloud-shapes#47]
### I tried this:

With a CartItem:
```yaml
_id: foo
_metadata:
  createdAt: 2025-02-14T11:42:53.5560742+01:00
  lastModified: 2025-02-17T12:34:03.4241562+01:00
  version: 12
orderId: order-1
productId: coca-cola-light-33cl
quantity: 4
product:
  _metadata:
    createdAt: 2025-02-14T10:18:24.4806873+01:00
    lastModified: 2025-02-14T10:18:24.4806920+01:00
    version: 1
  name: Coca Cola Light 33cl
  description: A 33cl can of Coca Cola Light
  price:
    value: 0.99
    currency: USD
```

Querying the API with:
`/api/cartItems?filters[orderId]=order-1`

### This happened:

The response is:
```json
{"items":[]}
```

### I expected this:

The response `items` to be populated and to have a `totalCount` property.
```json
{
    "items": [
        {
            "_id": "foo",
            "_metadata": {
                "createdAt": "2025-02-14T11:42:53.5560742+01:00",
                "lastModified": "2025-02-17T12:34:03.4241562+01:00",
                "version": 12
            },
            "orderId": "order-1",
            "productId": "coca-cola-light-33cl",
            "quantity": 4,
            "product": {
                "_metadata": {
                    "createdAt": "2025-02-14T10:18:24.4806873+01:00",
                    "lastModified": "2025-02-14T10:18:24.4806920+01:00",
                    "version": 1
                },
                "name": "Coca Cola Light 33cl",
                "description": "A 33cl can of Coca Cola Light",
                "price": {
                    "value": 0.99,
                    "currency": "USD"
                }
            }
        }
    ],
    "totalCount": 1
}
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.name: Bug Report 🐞
